services:
#    user_user.example:
#        class: User\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
   redirect.after.login:
      class: User\UserBundle\Redirection\AfterLoginRedirection
      arguments: ["@router"]