# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt #plaintext
    role_hierarchy:
            ROLE_CLIENT:      ROLE_USER
            ROLE_AGENT:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username





    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                require_previous_session: false
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path:            homepage
                success_handler: redirect.after.login
            logout:     #true
                target: /login
                #path:   homepage
                #path: security_logout
                                # The name of the route to redirect to after logging out
                #target: homepage
            anonymous:  true

    access_control:
                - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/admin/, role: ROLE_ADMIN }
                - { path: ^/affichage/, role: ROLE_CLIENT }



